[package]
name = "petgraph-schemes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

proptest = "1.0.0"

futures = "0.3.21"

tempdir = "0.3.7"

tokio = "1.0"
tokio-postgres = "0.7.6"
pg-embed = "0.6.5"