[package]
name = "schemes"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "3.2.8", features = ["derive"]}
colored = "2"
futures = "0.3.21"
proptest = "1.0.0"
regex = "1"
tokio = {version = "1.19", features = ["rt", "rt-multi-thread", "fs", "macros", "io-util"]}