[package]
name = "recursion"
version = "0.4.0"
edition = "2021"
description = "cache-aware stack safe recursion"
license = "MIT OR Apache-2.0"

[features]
default = []
experimental = []

[dependencies]
futures = "0.3"

